language: node_js

node_js:
  - '10'
  - '12'
  - '13'

cache: yarn

before_script: yarn install

script:
  - yarn test:unit
  - yarn test:lint
  - yarn build

jobs:
  include:

    - stage: "Coverage"
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - yarn test:unit
        - yarn test:coverage
        - ./cc-test-reporter after-build -r $CC_TEST_REPORTER_ID -t lcov coverage/lcov.info

    - stage: "Publish docs"
      if: branch = master
      script: yarn docs:publish    # usually you do not want to rerun any tests
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        local_dir: docs

    - stage: GitHub Release
      if: tag IS present
      script: skip
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        skip_cleanup: true
        on:
          tag: true

    - stage: "NPM deploy"
      before_script: yarn install
      script: yarn build     # usually you do not want to rerun any tests
      deploy:
        provider: npm
        email: lalung.alexandre@gmail.com
        api_key: $NPM_AUTH_TOKEN
        on:
          tag: true

code_climate:
  repo_token:
    secure: encrypted string
