language: node_js
node_js:
- '10'
- '12'
- '13'
cache: yarn
before_script: yarn install
script:
- yarn test:unit
- yarn test:lint
- yarn build
jobs:
  include:
  - stage: Coverage
    before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
      > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - "./cc-test-reporter before-build"
    script:
    - yarn test:unit
    - yarn test:coverage
    - "./cc-test-reporter after-build -r $CC_TEST_REPORTER_ID -t lcov coverage/lcov.info"
  - stage: Publish docs
    script: yarn docs:publish
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: "$GITHUB_TOKEN"
      keep_history: true
      local_dir: docs
      on:
        branch: master
  - stage: GitHub Release
    script: skip
    deploy:
      provider: releases
      api_key: "$GITHUB_TOKEN"
      skip_cleanup: true
      on:
        tags: true
code_climate:
  repo_token:
    secure: encrypted string
